# core/ruff.toml
target-version = "py310"
line-length = 88

[lint]
select = ["F", "E", "W", "I"]

# IGNORE ALL EXISTING TECHNICAL DEBT:
# E501: Line too long
# I001: Imports not sorted
# W291: Trailing whitespace
# W293: Blank lines with whitespace
# F401: Module imported but unused (The big blocker)
# F841: Local variable assigned but unused
ignore = ["E501", "I001", "W291", "W293", "F401", "F841"]

[format]
quote-style = "double"
indent-style = "space"
